name: nekoton_flutter_webview_example
description: Demonstrates how to use the nekoton_flutter_webview plugin.

publish_to: "none"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  nekoton_flutter_webview:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/js/
