name: nekoton_flutter_webview
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.0
  ffi: ^1.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.3.2
  freezed_annotation: ^0.14.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  json_annotation: ^4.0.0
  logger: ^1.0.0
  recase: ^4.0.0
  rxdart: ^0.27.0
  synchronized: ^3.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.3
  ffigen: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.2
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.broxus.nekoton_flutter_webview
        pluginClass: NekotonFlutterWebviewPlugin
      ios:
        pluginClass: NekotonFlutterWebviewPlugin

  assets:
    - assets/
    - assets/js/
